import { schema } from "./widget_GET.schema";
import superjson from "superjson";

import ReactDOMServer from "react-dom/server";

// This is a simplified build process for the widget script.
// In a real-world, production-grade application, this would be a pre-compiled, minified bundle
// generated by a build tool like Webpack or Vite. For this context, we'll dynamically
// generate the script string, which is less performant but demonstrates the concept.

// const getWidgetScript = (hostIdentifier: string) => `
// (function() {
//   "use strict";

//   // --- START: CSS for the widget ---
//   const css = \`
//     #qardhasana-widget-container {
//       all: initial;
//       font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
//       font-size: 16px;
//       line-height: 1.5;
//       color: #1a202c;
//       background-color: #ffffff;
//       border-radius: 12px;
//       padding: 24px;
//       box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1);
//       max-width: 400px;
//       margin: 0 auto;
//       box-sizing: border-box;
//       text-align: center;
//     }
//     #qardhasana-widget-container * {
//       box-sizing: border-box;
//     }
//     #qardhasana-widget-container h3 {
//       font-size: 1.25rem;
//       font-weight: 600;
//       margin: 0 0 8px 0;
//       color: #15803d; /* primary green */
//     }
//     #qardhasana-widget-container p {
//       font-size: 0.875rem;
//       color: #4a5568;
//       margin: 0 0 24px 0;
//     }
//     #qardhasana-widget-container .host-info {
//       background-color: #f7fafc;
//       border: 1px solid #e2e8f0;
//       border-radius: 8px;
//       padding: 16px;
//       margin-bottom: 24px;
//     }
//     #qardhasana-widget-container .host-name {
//       font-weight: 600;
//       font-size: 1rem;
//       color: #2d3748;
//       margin-bottom: 8px;
//     }
//     #qardhasana-widget-container .host-description {
//       font-size: 0.875rem;
//       color: #4a5568;
//       margin: 0;
//     }
//     #qardhasana-widget-container button {
//       width: 100%;
//       height: 48px;
//       border: none;
//       border-radius: 8px;
//       background-color: #15803d;
//       color: white;
//       font-size: 1rem;
//       font-weight: 500;
//       cursor: pointer;
//       transition: background-color 0.2s, transform 0.1s;
//       display: flex;
//       align-items: center;
//       justify-content: center;
//       gap: 8px;
//       text-decoration: none;
//     }
//     #qardhasana-widget-container button:hover {
//       background-color: #166534;
//       transform: translateY(-1px);
//     }
//     #qardhasana-widget-container button:active {
//       transform: translateY(0);
//     }
//     #qardhasana-widget-container .powered-by {
//       font-size: 0.75rem;
//       color: #718096;
//       margin-top: 16px;
//       text-align: center;
//     }
//     #qardhasana-widget-container .powered-by a {
//       color: #15803d;
//       text-decoration: none;
//     }
//     #qardhasana-widget-container .powered-by a:hover {
//       text-decoration: underline;
//     }
//   \`;
//   const styleSheet = document.createElement("style");
//   styleSheet.innerText = css;
//   document.head.appendChild(styleSheet);
//   // --- END: CSS for the widget ---

//   // --- START: Widget rendering logic ---
//   function renderWidget() {
//     const targetDiv = document.getElementById('qardhasana-widget');
//     if (!targetDiv) {
//       console.error('QardHasana Widget: Target div with id "qardhasana-widget" not found.');
//       return;
//     }

//     // Get the current domain for building the donation URL
//     const currentDomain = window.location.origin;
//     const donationUrl = \`\${currentDomain}/donate/\${encodeURIComponent('${hostIdentifier}')}\`;

//     function handleDonateClick() {
//       // Open the donation page in the same tab
//       window.open(donationUrl, '_blank');
//     }

//     function render() {
//       targetDiv.innerHTML = \`
//         <div id="qardhasana-widget-container">
//           <h3>Support ${hostIdentifier}</h3>
//           <p>Make a secure donation to support this cause. Your contribution makes a difference.</p>

//           <div class="host-info">
//             <div class="host-name">${hostIdentifier}</div>
//             <div class="host-description">Accepting donations through QardHasana</div>
//           </div>

//           <button type="button" onclick="this.onclick()">
//             <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
//               <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
//             </svg>
//             Donate Now
//           </button>

//           <div class="powered-by">
//             Powered by <a href="https://qardhasana.com" target="_blank">QardHasana</a>
//           </div>
//         </div>
//       \`;

//       // Add click handler to the button
//       const button = targetDiv.querySelector('button');
//       if (button) {
//         button.onclick = handleDonateClick;
//       }
//     }

//     render();
//   }

//   if (document.readyState === 'loading') {
//     document.addEventListener('DOMContentLoaded', renderWidget);
//   } else {
//     renderWidget();
//   }
//   // --- END: Widget rendering logic ---

// })();
// `;

const getWidgetScript = (hostIdentifier: string) =>
  `
(function () {
  "use strict";

  // --- START: CSS for the widget ---
  const css = \`
    /* Trigger Button Styles */
    #qardhasana-trigger-button {
      all: initial;
      position: fixed;
      bottom: 24px;
      right: 24px;
      z-index: 999999;
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }

    #qardhasana-trigger-button button {
      display: flex;
      align-items: center;
      gap: 10px;
      padding: 14px 24px;
      background: linear-gradient(135deg, #15803d 0%, #16a34a 100%);
      color: white;
      border: none;
      border-radius: 50px;
      font-size: 16px;
      font-weight: 600;
      cursor: pointer;
      box-shadow: 0 8px 24px rgba(21, 128, 61, 0.4);
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      font-family: inherit;
    }

    #qardhasana-trigger-button button:hover {
      transform: translateY(-2px);
      box-shadow: 0 12px 32px rgba(21, 128, 61, 0.5);
      background: linear-gradient(135deg, #166534 0%, #15803d 100%);
    }

    #qardhasana-trigger-button button:active {
      transform: translateY(0);
    }

    #qardhasana-trigger-button svg {
      animation: heartbeat 1.5s ease-in-out infinite;
    }

    @keyframes heartbeat {
      0%, 100% { transform: scale(1); }
      10%, 30% { transform: scale(1.1); }
      20%, 40% { transform: scale(1); }
    }

    /* Modal Overlay */
    #qardhasana-modal-overlay {
      all: initial;
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, 0.6);
      backdrop-filter: blur(4px);
      z-index: 1000000;
      display: flex;
      align-items: center;
      justify-content: center;
      opacity: 0;
      transition: opacity 0.3s ease;
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }

    #qardhasana-modal-overlay.show {
      opacity: 1;
    }

    /* Modal Container */
    #qardhasana-widget-container {
      all: initial;
      font-family: 'Inter', sans-serif;
      font-size: 16px;
      background: linear-gradient(to bottom, #ffffff 0%, #f8fffe 100%);
      border-radius: 20px;
      max-width: 480px;
      width: 90%;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
      position: relative;
      transform: scale(0.9);
      transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      text-align: center;
      padding: 32px;
    }

    #qardhasana-modal-overlay.show #qardhasana-widget-container {
      transform: scale(1);
    }

    .widget-title { font-size: 32px; font-weight: 700; margin: 0 0 12px; }
    .widget-subtitle { font-size: 18px; color: #6b7280; margin: 0 0 32px; }
    .donation-card { background: white; border-radius: 16px; padding: 32px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); margin-bottom:16px; }
    .card-title { font-size: 22px; font-weight:700; color:#15803d; margin-bottom:8px; }
    .card-description { font-size:16px; color:#6b7280; margin-bottom:24px; }
    .form-group { margin-bottom:24px; text-align:left; }
    .form-label { display:block; font-weight:600; margin-bottom:8px; }
    .form-input { width:100%; padding:14px 16px; font-size:16px; border:2px solid #e5e7eb; border-radius:8px; background:#f9fafb; color:#1a202c; transition: all 0.2s; }
    .form-input:focus { outline:none; border-color:#3d7a77; background:white; }
    .checkbox-container { display:flex; align-items:flex-start; gap:12px; margin-bottom:24px; text-align:left; }
    .checkbox-input { width:20px; height:20px; margin-top:2px; cursor:pointer; flex-shrink:0; }
    .checkbox-label { font-size:14px; color:#4b5563; line-height:1.5; cursor:pointer; }
    .submit-button { width:100%; background: linear-gradient(135deg, #15803d 0%, #16a34a 100%); color:white; padding:16px; border:none; border-radius:10px; font-size:18px; font-weight:600; cursor:pointer; transition: all 0.3s; }
    .submit-button:hover { transform:translateY(-2px); box-shadow:0 10px 20px rgba(61,122,119,0.3); }
    .submit-button:active { transform:translateY(0); }
  \`;

  const styleSheet = document.createElement("style");
  styleSheet.innerText = css;
  document.head.appendChild(styleSheet);

  // --- Widget rendering ---
  function renderWidget() {
    const hostIdentifier = "sample"; // Replace with your dynamic identifier if needed

    // Trigger button
    const triggerContainer = document.createElement("div");
    triggerContainer.id = "qardhasana-trigger-button";
    triggerContainer.innerHTML = "\
      <button type='button'>\
        <svg width='20' height='20' viewBox='0 0 24 24' fill='currentColor'>\
          <path d='M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z'/>\
        </svg>\
        Support\
      </button>";

    document.body.appendChild(triggerContainer);

    // Modal overlay
    const modalOverlay = document.createElement("div");
    modalOverlay.id = "qardhasana-modal-overlay";
    modalOverlay.style.display = "none";

    const donationUrl = "https://example.com/donate/" + encodeURIComponent(hostIdentifier);

    modalOverlay.innerHTML = "\
      <div id='qardhasana-widget-container'>\
        <h1 class='widget-title'>Support sample</h1>\
        <p class='widget-subtitle'>Your contribution helps cover their monthly overheads.</p>\
        <div class='donation-card'>\
          <h2 class='card-title'>Support with QardHasana</h2>\
          <p class='card-description'>Support this cause with a donation. Your contribution is valued.</p>\
          <form id='donation-form'>\
            <div class='form-group'>\
              <label class='form-label' for='amount'>Amount (USD)</label>\
              <input type='number' id='amount' class='form-input' placeholder='Enter amount between $10 and $500' min='10' max='500' required />\
            </div>\
            <div class='form-group'>\
              <label class='form-label' for='name'>Name (Optional)</label>\
              <input type='text' id='name' class='form-input' placeholder='Your name' />\
            </div>\
            <div class='checkbox-container'>\
              <input type='checkbox' id='donation-intent' class='checkbox-input' required />\
              <label for='donation-intent' class='checkbox-label'>I am donating purely out of admiration and willingness to help, not for profit.</label>\
            </div>\
            <button type='submit' class='submit-button'>Proceed to Payment</button>\
          </form>\
        </div>\
      </div>";

    document.body.appendChild(modalOverlay);

    function openModal() {
      modalOverlay.style.display = "flex";
      setTimeout(() => modalOverlay.classList.add("show"), 10);
    }

    function closeModal() {
      modalOverlay.classList.remove("show");
      setTimeout(() => (modalOverlay.style.display = "none"), 300);
    }

    function donate() {
      window.open(donationUrl, "_blank");
      closeModal();
    }

    triggerContainer.querySelector("button").addEventListener("click", openModal);
    modalOverlay.querySelector("#donation-form").addEventListener("submit", function(e) {
      e.preventDefault();
      donate();
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", renderWidget);
  } else {
    renderWidget();
  }
})();
`;

export async function handle(request: Request) {
  try {
    const url = new URL(request.url);
    const validatedInput = schema.parse({
      hostIdentifier: url.searchParams.get("hostIdentifier"),
    });

    const scriptContent = getWidgetScript("Sample");

    return new Response(scriptContent, {
      headers: {
        "Content-Type": "application/javascript; charset=utf-8",
        "Cache-Control": "public, max-age=3600", // Cache for 1 hour
      },
    });
  } catch (error) {
    console.error("Failed to generate widget script:", error);
    const errorMessage =
      error instanceof Error ? error.message : "An unknown error occurred";
    return new Response(superjson.stringify({ error: errorMessage }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }
}

