import { schema } from "./widget_GET.schema";
import superjson from 'superjson';

// This is a simplified build process for the widget script.
// In a real-world, production-grade application, this would be a pre-compiled, minified bundle
// generated by a build tool like Webpack or Vite. For this context, we'll dynamically
// generate the script string, which is less performant but demonstrates the concept.

const getWidgetScript = (hostIdentifier: string) => `
(function() {
  "use strict";

  // --- START: CSS for the widget ---
  const css = \`
    #qardhasana-widget-container {
      all: initial;
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      font-size: 16px;
      line-height: 1.5;
      color: #1a202c;
      background-color: #ffffff;
      border-radius: 12px;
      padding: 24px;
      box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1);
      max-width: 400px;
      margin: 0 auto;
      box-sizing: border-box;
      text-align: center;
    }
    #qardhasana-widget-container * {
      box-sizing: border-box;
    }
    #qardhasana-widget-container h3 {
      font-size: 1.25rem;
      font-weight: 600;
      margin: 0 0 8px 0;
      color: #15803d; /* primary green */
    }
    #qardhasana-widget-container p {
      font-size: 0.875rem;
      color: #4a5568;
      margin: 0 0 24px 0;
    }
    #qardhasana-widget-container .host-info {
      background-color: #f7fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 24px;
    }
    #qardhasana-widget-container .host-name {
      font-weight: 600;
      font-size: 1rem;
      color: #2d3748;
      margin-bottom: 8px;
    }
    #qardhasana-widget-container .host-description {
      font-size: 0.875rem;
      color: #4a5568;
      margin: 0;
    }
    #qardhasana-widget-container button {
      width: 100%;
      height: 48px;
      border: none;
      border-radius: 8px;
      background-color: #15803d;
      color: white;
      font-size: 1rem;
      font-weight: 500;
      cursor: pointer;
      transition: background-color 0.2s, transform 0.1s;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      text-decoration: none;
    }
    #qardhasana-widget-container button:hover {
      background-color: #166534;
      transform: translateY(-1px);
    }
    #qardhasana-widget-container button:active {
      transform: translateY(0);
    }
    #qardhasana-widget-container .powered-by {
      font-size: 0.75rem;
      color: #718096;
      margin-top: 16px;
      text-align: center;
    }
    #qardhasana-widget-container .powered-by a {
      color: #15803d;
      text-decoration: none;
    }
    #qardhasana-widget-container .powered-by a:hover {
      text-decoration: underline;
    }
  \`;
  const styleSheet = document.createElement("style");
  styleSheet.innerText = css;
  document.head.appendChild(styleSheet);
  // --- END: CSS for the widget ---

  // --- START: Widget rendering logic ---
  function renderWidget() {
    const targetDiv = document.getElementById('qardhasana-widget');
    if (!targetDiv) {
      console.error('QardHasana Widget: Target div with id "qardhasana-widget" not found.');
      return;
    }

    // Get the current domain for building the donation URL
    const currentDomain = window.location.origin;
    const donationUrl = \`\${currentDomain}/donate/\${encodeURIComponent('${hostIdentifier}')}\`;

    function handleDonateClick() {
      // Open the donation page in the same tab
      window.open(donationUrl, '_blank');
    }

    function render() {
      targetDiv.innerHTML = \`
        <div id="qardhasana-widget-container">
          <h3>Support ${hostIdentifier}</h3>
          <p>Make a secure donation to support this cause. Your contribution makes a difference.</p>
          
          <div class="host-info">
            <div class="host-name">${hostIdentifier}</div>
            <div class="host-description">Accepting donations through QardHasana</div>
          </div>
          
          <button type="button" onclick="this.onclick()">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
            </svg>
            Donate Now
          </button>
          
          <div class="powered-by">
            Powered by <a href="https://qardhasana.com" target="_blank">QardHasana</a>
          </div>
        </div>
      \`;
      
      // Add click handler to the button
      const button = targetDiv.querySelector('button');
      if (button) {
        button.onclick = handleDonateClick;
      }
    }
    
    render();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderWidget);
  } else {
    renderWidget();
  }
  // --- END: Widget rendering logic ---

})();
`;

export async function handle(request: Request) {
  try {
    const url = new URL(request.url);
    const validatedInput = schema.parse({
      hostIdentifier: url.searchParams.get('hostIdentifier'),
    });

    const scriptContent = getWidgetScript(validatedInput.hostIdentifier);

    return new Response(scriptContent, {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'public, max-age=3600', // Cache for 1 hour
      },
    });
  } catch (error) {
    console.error("Failed to generate widget script:", error);
    const errorMessage = error instanceof Error ? error.message : "An unknown error occurred";
    return new Response(superjson.stringify({ error: errorMessage }), { 
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}