// import { schema } from "./widget_GET.schema";
// import superjson from "superjson";

// import ReactDOMServer from "react-dom/server";

// // This is a simplified build process for the widget script.
// // In a real-world, production-grade application, this would be a pre-compiled, minified bundle
// // generated by a build tool like Webpack or Vite. For this context, we'll dynamically
// // generate the script string, which is less performant but demonstrates the concept.

// // const getWidgetScript = (hostIdentifier: string) => `
// // (function() {
// //   "use strict";

// //   // --- START: CSS for the widget ---
// //   const css = \`
// //     #qardhasana-widget-container {
// //       all: initial;
// //       font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
// //       font-size: 16px;
// //       line-height: 1.5;
// //       color: #1a202c;
// //       background-color: #ffffff;
// //       border-radius: 12px;
// //       padding: 24px;
// //       box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1);
// //       max-width: 400px;
// //       margin: 0 auto;
// //       box-sizing: border-box;
// //       text-align: center;
// //     }
// //     #qardhasana-widget-container * {
// //       box-sizing: border-box;
// //     }
// //     #qardhasana-widget-container h3 {
// //       font-size: 1.25rem;
// //       font-weight: 600;
// //       margin: 0 0 8px 0;
// //       color: #15803d; /* primary green */
// //     }
// //     #qardhasana-widget-container p {
// //       font-size: 0.875rem;
// //       color: #4a5568;
// //       margin: 0 0 24px 0;
// //     }
// //     #qardhasana-widget-container .host-info {
// //       background-color: #f7fafc;
// //       border: 1px solid #e2e8f0;
// //       border-radius: 8px;
// //       padding: 16px;
// //       margin-bottom: 24px;
// //     }
// //     #qardhasana-widget-container .host-name {
// //       font-weight: 600;
// //       font-size: 1rem;
// //       color: #2d3748;
// //       margin-bottom: 8px;
// //     }
// //     #qardhasana-widget-container .host-description {
// //       font-size: 0.875rem;
// //       color: #4a5568;
// //       margin: 0;
// //     }
// //     #qardhasana-widget-container button {
// //       width: 100%;
// //       height: 48px;
// //       border: none;
// //       border-radius: 8px;
// //       background-color: #15803d;
// //       color: white;
// //       font-size: 1rem;
// //       font-weight: 500;
// //       cursor: pointer;
// //       transition: background-color 0.2s, transform 0.1s;
// //       display: flex;
// //       align-items: center;
// //       justify-content: center;
// //       gap: 8px;
// //       text-decoration: none;
// //     }
// //     #qardhasana-widget-container button:hover {
// //       background-color: #166534;
// //       transform: translateY(-1px);
// //     }
// //     #qardhasana-widget-container button:active {
// //       transform: translateY(0);
// //     }
// //     #qardhasana-widget-container .powered-by {
// //       font-size: 0.75rem;
// //       color: #718096;
// //       margin-top: 16px;
// //       text-align: center;
// //     }
// //     #qardhasana-widget-container .powered-by a {
// //       color: #15803d;
// //       text-decoration: none;
// //     }
// //     #qardhasana-widget-container .powered-by a:hover {
// //       text-decoration: underline;
// //     }
// //   \`;
// //   const styleSheet = document.createElement("style");
// //   styleSheet.innerText = css;
// //   document.head.appendChild(styleSheet);
// //   // --- END: CSS for the widget ---

// //   // --- START: Widget rendering logic ---
// //   function renderWidget() {
// //     const targetDiv = document.getElementById('qardhasana-widget');
// //     if (!targetDiv) {
// //       console.error('QardHasana Widget: Target div with id "qardhasana-widget" not found.');
// //       return;
// //     }

// //     // Get the current domain for building the donation URL
// //     const currentDomain = window.location.origin;
// //     const donationUrl = \`\${currentDomain}/donate/\${encodeURIComponent('${hostIdentifier}')}\`;

// //     function handleDonateClick() {
// //       // Open the donation page in the same tab
// //       window.open(donationUrl, '_blank');
// //     }

// //     function render() {
// //       targetDiv.innerHTML = \`
// //         <div id="qardhasana-widget-container">
// //           <h3>Support ${hostIdentifier}</h3>
// //           <p>Make a secure donation to support this cause. Your contribution makes a difference.</p>

// //           <div class="host-info">
// //             <div class="host-name">${hostIdentifier}</div>
// //             <div class="host-description">Accepting donations through QardHasana</div>
// //           </div>

// //           <button type="button" onclick="this.onclick()">
// //             <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
// //               <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
// //             </svg>
// //             Donate Now
// //           </button>

// //           <div class="powered-by">
// //             Powered by <a href="https://qardhasana.com" target="_blank">QardHasana</a>
// //           </div>
// //         </div>
// //       \`;

// //       // Add click handler to the button
// //       const button = targetDiv.querySelector('button');
// //       if (button) {
// //         button.onclick = handleDonateClick;
// //       }
// //     }

// //     render();
// //   }

// //   if (document.readyState === 'loading') {
// //     document.addEventListener('DOMContentLoaded', renderWidget);
// //   } else {
// //     renderWidget();
// //   }
// //   // --- END: Widget rendering logic ---

// // })();
// // `;

// const getWidgetScript = (hostIdentifier: string) =>
//   `
// (function () {
//   "use strict";

//   // --- START: CSS for the widget ---
//   const css = \`
//     /* Trigger Button Styles */
//     #qardhasana-trigger-button {
//       all: initial;
//       position: fixed;
//       bottom: 24px;
//       right: 24px;
//       z-index: 999999;
//       font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
//     }

//     #qardhasana-trigger-button button {
//       display: flex;
//       align-items: center;
//       gap: 10px;
//       padding: 14px 24px;
//       background: linear-gradient(135deg, #15803d 0%, #16a34a 100%);
//       color: white;
//       border: none;
//       border-radius: 50px;
//       font-size: 16px;
//       font-weight: 600;
//       cursor: pointer;
//       box-shadow: 0 8px 24px rgba(21, 128, 61, 0.4);
//       transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
//       font-family: inherit;
//     }

//     #qardhasana-trigger-button button:hover {
//       transform: translateY(-2px);
//       box-shadow: 0 12px 32px rgba(21, 128, 61, 0.5);
//       background: linear-gradient(135deg, #166534 0%, #15803d 100%);
//     }

//     #qardhasana-trigger-button button:active {
//       transform: translateY(0);
//     }

//     #qardhasana-trigger-button svg {
//       animation: heartbeat 1.5s ease-in-out infinite;
//     }

//     @keyframes heartbeat {
//       0%, 100% { transform: scale(1); }
//       10%, 30% { transform: scale(1.1); }
//       20%, 40% { transform: scale(1); }
//     }

//     /* Modal Overlay */
//     #qardhasana-modal-overlay {
//       all: initial;
//       position: fixed;
//       top: 0;
//       left: 0;
//       right: 0;
//       bottom: 0;
//       background-color: rgba(0, 0, 0, 0.6);
//       backdrop-filter: blur(4px);
//       z-index: 1000000;
//       display: flex;
//       align-items: center;
//       justify-content: center;
//       opacity: 0;
//       transition: opacity 0.3s ease;
//       font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
//     }

//     #qardhasana-modal-overlay.show {
//       opacity: 1;
//     }

//     /* Modal Container */
//     #qardhasana-widget-container {
//       all: initial;
//       font-family: 'Inter', sans-serif;
//       font-size: 16px;
//       background: linear-gradient(to bottom, #ffffff 0%, #f8fffe 100%);
//       border-radius: 20px;
//       max-width: 480px;
//       width: 90%;
//       box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
//       position: relative;
//       transform: scale(0.9);
//       transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
//       text-align: center;
//       padding: 32px;
//     }

//     #qardhasana-modal-overlay.show #qardhasana-widget-container {
//       transform: scale(1);
//     }

//     .widget-title { font-size: 32px; font-weight: 700; margin: 0 0 12px; }
//     .widget-subtitle { font-size: 18px; color: #6b7280; margin: 0 0 32px; }
//     .donation-card { background: white; border-radius: 16px; padding: 32px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); margin-bottom:16px; }
//     .card-title { font-size: 22px; font-weight:700; color:#15803d; margin-bottom:8px; }
//     .card-description { font-size:16px; color:#6b7280; margin-bottom:24px; }
//     .form-group { margin-bottom:24px; text-align:left; }
//     .form-label { display:block; font-weight:600; margin-bottom:8px; }
//     .form-input { width:100%; padding:14px 16px; font-size:16px; border:2px solid #e5e7eb; border-radius:8px; background:#f9fafb; color:#1a202c; transition: all 0.2s; }
//     .form-input:focus { outline:none; border-color:#3d7a77; background:white; }
//     .checkbox-container { display:flex; align-items:flex-start; gap:12px; margin-bottom:24px; text-align:left; }
//     .checkbox-input { width:20px; height:20px; margin-top:2px; cursor:pointer; flex-shrink:0; }
//     .checkbox-label { font-size:14px; color:#4b5563; line-height:1.5; cursor:pointer; }
//     .submit-button { width:100%; background: linear-gradient(135deg, #15803d 0%, #16a34a 100%); color:white; padding:16px; border:none; border-radius:10px; font-size:18px; font-weight:600; cursor:pointer; transition: all 0.3s; }
//     .submit-button:hover { transform:translateY(-2px); box-shadow:0 10px 20px rgba(61,122,119,0.3); }
//     .submit-button:active { transform:translateY(0); }
//   \`;

//   const styleSheet = document.createElement("style");
//   styleSheet.innerText = css;
//   document.head.appendChild(styleSheet);

//   // --- Widget rendering ---
//   function renderWidget() {
//     const hostIdentifier = "sample"; // Replace with your dynamic identifier if needed

//     // Trigger button
//     const triggerContainer = document.createElement("div");
//     triggerContainer.id = "qardhasana-trigger-button";
//     triggerContainer.innerHTML = "\
//       <button type='button'>\
//         <svg width='20' height='20' viewBox='0 0 24 24' fill='currentColor'>\
//           <path d='M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z'/>\
//         </svg>\
//         Support\
//       </button>";

//     document.body.appendChild(triggerContainer);

//     // Modal overlay
//     const modalOverlay = document.createElement("div");
//     modalOverlay.id = "qardhasana-modal-overlay";
//     modalOverlay.style.display = "none";

//     const donationUrl = "https://example.com/donate/" + encodeURIComponent(hostIdentifier);

//     modalOverlay.innerHTML = "\
//       <div id='qardhasana-widget-container'>\
//         <h1 class='widget-title'>Support sample</h1>\
//         <p class='widget-subtitle'>Your contribution helps cover their monthly overheads.</p>\
//         <div class='donation-card'>\
//           <h2 class='card-title'>Support with QardHasana</h2>\
//           <p class='card-description'>Support this cause with a donation. Your contribution is valued.</p>\
//           <form id='donation-form'>\
//             <div class='form-group'>\
//               <label class='form-label' for='amount'>Amount (USD)</label>\
//               <input type='number' id='amount' class='form-input' placeholder='Enter amount between $10 and $500' min='10' max='500' required />\
//             </div>\
//             <div class='form-group'>\
//               <label class='form-label' for='name'>Name (Optional)</label>\
//               <input type='text' id='name' class='form-input' placeholder='Your name' />\
//             </div>\
//             <div class='checkbox-container'>\
//               <input type='checkbox' id='donation-intent' class='checkbox-input' required />\
//               <label for='donation-intent' class='checkbox-label'>I am donating purely out of admiration and willingness to help, not for profit.</label>\
//             </div>\
//             <button type='submit' class='submit-button'>Proceed to Payment</button>\
//           </form>\
//         </div>\
//       </div>";

//     document.body.appendChild(modalOverlay);

//     function openModal() {
//       modalOverlay.style.display = "flex";
//       setTimeout(() => modalOverlay.classList.add("show"), 10);
//     }

//     function closeModal() {
//       modalOverlay.classList.remove("show");
//       setTimeout(() => (modalOverlay.style.display = "none"), 300);
//     }

//     function donate() {
//       window.open(donationUrl, "_blank");
//       closeModal();
//     }

//     triggerContainer.querySelector("button").addEventListener("click", openModal);
//     modalOverlay.querySelector("#donation-form").addEventListener("submit", function(e) {
//       e.preventDefault();
//       donate();
//     });
//   }

//   if (document.readyState === "loading") {
//     document.addEventListener("DOMContentLoaded", renderWidget);
//   } else {
//     renderWidget();
//   }
// })();
// `;

// export async function handle(request: Request) {
//   try {
//     const url = new URL(request.url);
//     const validatedInput = schema.parse({
//       hostIdentifier: url.searchParams.get("hostIdentifier"),
//     });

//     const scriptContent = getWidgetScript("Sample");

//     return new Response(scriptContent, {
//       headers: {
//         "Content-Type": "application/javascript; charset=utf-8",
//         "Cache-Control": "public, max-age=3600", // Cache for 1 hour
//       },
//     });
//   } catch (error) {
//     console.error("Failed to generate widget script:", error);
//     const errorMessage =
//       error instanceof Error ? error.message : "An unknown error occurred";
//     return new Response(superjson.stringify({ error: errorMessage }), {
//       status: 400,
//       headers: { "Content-Type": "application/json" },
//     });
//   }
// }

import { schema } from "./widget_GET.schema";
import superjson from "superjson";
import { getServerUserSession } from "../helpers/getServerUserSession";

// Widget script generator supporting both donations and loans
const getWidgetScript = (
  hostIdentifier: string,
  widgetData: {
    title: string;
    goalAmount: number;
    repaymentCapableAmount: number;
    currentAmount: number;
  },
) => `
(function () {
  "use strict";

  // --- START: CSS for the widget ---
  const css = \`
    /* Trigger Button Styles */
    #qardhasana-trigger-button {
      all: initial;
      position: fixed;
      bottom: 24px;
      right: 24px;
      z-index: 999999;
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }

    #qardhasana-trigger-button button {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 16px 28px;
      background: linear-gradient(135deg, #15803d 0%, #16a34a 100%);
      color: white;
      border: none;
      border-radius: 50px;
      font-size: 16px;
      font-weight: 600;
      cursor: pointer;
      box-shadow: 0 8px 32px rgba(21, 128, 61, 0.3), 0 0 0 0 rgba(21, 128, 61, 0.4);
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      font-family: inherit;
      animation: pulse-shadow 2s infinite;
    }

    @keyframes pulse-shadow {
      0%, 100% {
        box-shadow: 0 8px 32px rgba(21, 128, 61, 0.3), 0 0 0 0 rgba(21, 128, 61, 0.4);
      }
      50% {
        box-shadow: 0 8px 32px rgba(21, 128, 61, 0.4), 0 0 0 8px rgba(21, 128, 61, 0);
      }
    }

    #qardhasana-trigger-button button:hover {
      transform: translateY(-3px) scale(1.02);
      box-shadow: 0 12px 40px rgba(21, 128, 61, 0.4);
      background: linear-gradient(135deg, #166534 0%, #15803d 100%);
    }

    #qardhasana-trigger-button button:active {
      transform: translateY(-1px) scale(1);
    }

    #qardhasana-trigger-button svg {
      animation: heartbeat 1.5s ease-in-out infinite;
    }

    @keyframes heartbeat {
      0%, 100% { transform: scale(1); }
      10%, 30% { transform: scale(1.15); }
      20%, 40% { transform: scale(1); }
    }

    /* Modal Overlay */
    #qardhasana-modal-overlay {
      all: initial;
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, 0.7);
      backdrop-filter: blur(8px);
      -webkit-backdrop-filter: blur(8px);
      z-index: 1000000;
      display: flex;
      align-items: center;
      justify-content: center;
      opacity: 0;
      transition: opacity 0.3s ease;
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      padding: 20px;
    }

    #qardhasana-modal-overlay.show {
      opacity: 1;
    }

    /* Modal Container */
    #qardhasana-widget-container {
      all: initial;
      font-family: 'Inter', sans-serif;
      font-size: 16px;
      background: linear-gradient(145deg, #ffffff 0%, #f0fdf4 100%);
      border-radius: 24px;
      max-width: 520px;
      width: 100%;
      max-height: 90vh;
      overflow-y: auto;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25), 0 0 0 1px rgba(255, 255, 255, 0.1);
      position: relative;
      transform: scale(0.9) translateY(20px);
      transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      text-align: center;
      padding: 40px;
      box-sizing: border-box;
    }

    #qardhasana-widget-container * {
      box-sizing: border-box;
    }

    #qardhasana-modal-overlay.show #qardhasana-widget-container {
      transform: scale(1) translateY(0);
    }

    /* Close Button */
    .close-button {
      position: absolute;
      top: 20px;
      right: 20px;
      width: 36px;
      height: 36px;
      border: none;
      background: rgba(0, 0, 0, 0.05);
      border-radius: 50%;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      transition: all 0.2s;
      padding: 0;
    }

    .close-button:hover {
      background: rgba(0, 0, 0, 0.1);
      transform: rotate(90deg);
    }

    .close-button svg {
      width: 20px;
      height: 20px;
      stroke: #6b7280;
    }

    /* Header */
    .widget-header {
      margin-bottom: 32px;
    }

    .widget-title {
      font-size: 28px;
      font-weight: 700;
      margin: 0 0 8px;
      color: #0f172a;
      line-height: 1.2;
    }

    .widget-subtitle {
      font-size: 16px;
      color: #64748b;
      margin: 0;
      line-height: 1.5;
    }

    /* Progress Section */
    .progress-section {
      background: rgba(255, 255, 255, 0.7);
      backdrop-filter: blur(10px);
      -webkit-backdrop-filter: blur(10px);
      border: 1px solid rgba(21, 128, 61, 0.1);
      border-radius: 16px;
      padding: 24px;
      margin-bottom: 24px;
    }

    .progress-stats {
      display: flex;
      justify-content: space-between;
      margin-bottom: 16px;
      gap: 16px;
    }

    .stat {
      flex: 1;
      text-align: left;
    }

    .stat-label {
      font-size: 12px;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      font-weight: 600;
      margin-bottom: 4px;
    }

    .stat-value {
      font-size: 24px;
      font-weight: 700;
      color: #15803d;
    }

    .stat-value.secondary {
      color: #0f172a;
    }

    /* Progress Bar */
    .progress-bar-container {
      width: 100%;
      height: 12px;
      background: rgba(21, 128, 61, 0.1);
      border-radius: 20px;
      overflow: hidden;
      position: relative;
    }

    .progress-bar-fill {
      height: 100%;
      background: linear-gradient(90deg, #15803d 0%, #16a34a 100%);
      border-radius: 20px;
      transition: width 0.6s cubic-bezier(0.4, 0, 0.2, 1);
      position: relative;
      overflow: hidden;
    }

    .progress-bar-fill::after {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.3), transparent);
      animation: shimmer 2s infinite;
    }

    @keyframes shimmer {
      0% { transform: translateX(-100%); }
      100% { transform: translateX(100%); }
    }

    /* Action Tabs */
    .action-tabs {
      display: flex;
      gap: 8px;
      margin-bottom: 24px;
      background: rgba(0, 0, 0, 0.03);
      padding: 6px;
      border-radius: 12px;
    }

    .tab-button {
      flex: 1;
      padding: 12px 20px;
      border: none;
      background: transparent;
      border-radius: 8px;
      font-size: 15px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.2s;
      color: #64748b;
      font-family: inherit;
    }

    .tab-button.active {
      background: white;
      color: #15803d;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
    }

    .tab-button:hover:not(.active) {
      background: rgba(255, 255, 255, 0.5);
    }

    /* Form */
    .donation-form {
      text-align: left;
    }

    .form-group {
      margin-bottom: 20px;
    }

    .form-label {
      display: block;
      font-weight: 600;
      margin-bottom: 8px;
      color: #0f172a;
      font-size: 14px;
    }

    .form-input {
      width: 100%;
      padding: 14px 16px;
      font-size: 16px;
      border: 2px solid #e2e8f0;
      border-radius: 10px;
      background: white;
      color: #0f172a;
      transition: all 0.2s;
      font-family: inherit;
    }

    .form-input:focus {
      outline: none;
      border-color: #15803d;
      box-shadow: 0 0 0 3px rgba(21, 128, 61, 0.1);
    }

    .form-input::placeholder {
      color: #94a3b8;
    }

    .amount-suggestions {
      display: flex;
      gap: 8px;
      margin-top: 8px;
      flex-wrap: wrap;
    }

    .amount-chip {
      padding: 8px 16px;
      border: 2px solid #e2e8f0;
      border-radius: 8px;
      background: white;
      cursor: pointer;
      transition: all 0.2s;
      font-size: 14px;
      font-weight: 600;
      color: #64748b;
    }

    .amount-chip:hover {
      border-color: #15803d;
      color: #15803d;
      transform: translateY(-2px);
    }

    /* Info Box */
    .info-box {
      background: linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%);
      border: 1px solid #a7f3d0;
      border-radius: 12px;
      padding: 16px;
      margin-bottom: 20px;
      display: flex;
      gap: 12px;
      align-items: flex-start;
    }

    .info-box svg {
      flex-shrink: 0;
      margin-top: 2px;
    }

    .info-box-text {
      font-size: 13px;
      color: #065f46;
      line-height: 1.5;
      margin: 0;
      text-align: left;
    }

    /* Checkbox */
    .checkbox-container {
      display: flex;
      align-items: flex-start;
      gap: 12px;
      margin-bottom: 24px;
    }

    .checkbox-input {
      width: 20px;
      height: 20px;
      margin-top: 2px;
      cursor: pointer;
      flex-shrink: 0;
      accent-color: #15803d;
    }

    .checkbox-label {
      font-size: 13px;
      color: #475569;
      line-height: 1.5;
      cursor: pointer;
      text-align: left;
    }

    /* Submit Button */
    .submit-button {
      width: 100%;
      background: linear-gradient(135deg, #15803d 0%, #16a34a 100%);
      color: white;
      padding: 16px;
      border: none;
      border-radius: 12px;
      font-size: 16px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      font-family: inherit;
      box-shadow: 0 4px 12px rgba(21, 128, 61, 0.3);
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
    }

    .submit-button:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 20px rgba(21, 128, 61, 0.4);
    }

    .submit-button:active {
      transform: translateY(0);
    }

    .submit-button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
      transform: none;
    }

    /* Powered By */
    .powered-by {
      margin-top: 24px;
      font-size: 12px;
      color: #94a3b8;
      text-align: center;
    }

    .powered-by a {
      color: #15803d;
      text-decoration: none;
      font-weight: 600;
    }

    .powered-by a:hover {
      text-decoration: underline;
    }

    /* Mobile Responsiveness */
    @media (max-width: 640px) {
      #qardhasana-widget-container {
        padding: 24px;
      }

      .widget-title {
        font-size: 24px;
      }

      .stat-value {
        font-size: 20px;
      }

      .progress-stats {
        flex-direction: column;
        gap: 12px;
      }
    }
  \`;

  const styleSheet = document.createElement("style");
  styleSheet.innerText = css;
  document.head.appendChild(styleSheet);

  // --- Widget rendering ---
  function renderWidget() {
    const widgetData = ${JSON.stringify(widgetData)};
    const hostIdentifier = "${hostIdentifier}";
    const progressPercentage = Math.min((widgetData.currentAmount / widgetData.goalAmount) * 100, 100);
    const remainingAmount = Math.max(widgetData.goalAmount - widgetData.currentAmount, 0);

    // Trigger button
    const triggerContainer = document.createElement("div");
    triggerContainer.id = "qardhasana-trigger-button";
    triggerContainer.innerHTML = \`
      <button type='button'>
        <svg width='20' height='20' viewBox='0 0 24 24' fill='currentColor'>
          <path d='M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z'/>
        </svg>
        Support
      </button>\`;

    document.body.appendChild(triggerContainer);

    // Modal overlay
    const modalOverlay = document.createElement("div");
    modalOverlay.id = "qardhasana-modal-overlay";
    modalOverlay.style.display = "none";

    modalOverlay.innerHTML = \`
      <div id='qardhasana-widget-container'>
        <button type='button' class='close-button' id='close-modal'>
          <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
            <path d='M18 6L6 18M6 6l12 12'/>
          </svg>
        </button>

        <div class='widget-header'>
          <h1 class='widget-title'>\${widgetData.title}</h1>
          <p class='widget-subtitle'>Support this cause through QardHasana</p>
        </div>

        <div class='progress-section'>
          <div class='progress-stats'>
            <div class='stat'>
              <div class='stat-label'>Raised</div>
              <div class='stat-value'>$\${widgetData.currentAmount.toLocaleString()}</div>
            </div>
            <div class='stat'>
              <div class='stat-label'>Goal</div>
              <div class='stat-value secondary'>$\${widgetData.goalAmount.toLocaleString()}</div>
            </div>
          </div>
          <div class='progress-bar-container'>
            <div class='progress-bar-fill' style='width: \${progressPercentage}%'></div>
          </div>
        </div>

        <div class='action-tabs'>
          <button type='button' class='tab-button active' data-tab='donate'>
            <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
</svg> Support</span>
          </button>
          <button type='button' class='tab-button' data-tab='loan'>
            <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640" width="16" height="16"><!--!Font Awesome Free 7.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M300.9 149.2L184.3 278.8C179.7 283.9 179.9 291.8 184.8 296.7C215.3 327.2 264.8 327.2 295.3 296.7L327.1 264.9C331.3 260.7 336.6 258.4 342 258C348.8 257.4 355.8 259.7 361 264.9L537.6 440L608 384L608 96L496 160L472.2 144.1C456.4 133.6 437.9 128 418.9 128L348.5 128C347.4 128 346.2 128 345.1 128.1C328.2 129 312.3 136.6 300.9 149.2zM148.6 246.7L255.4 128L215.8 128C190.3 128 165.9 138.1 147.9 156.1L144 160L32 96L32 384L188.4 514.3C211.4 533.5 240.4 544 270.3 544L286 544L279 537C269.6 527.6 269.6 512.4 279 503.1C288.4 493.8 303.6 493.7 312.9 503.1L353.9 544.1L362.9 544.1C382 544.1 400.7 539.8 417.7 531.8L391 505C381.6 495.6 381.6 480.4 391 471.1C400.4 461.8 415.6 461.7 424.9 471.1L456.9 503.1L474.4 485.6C483.3 476.7 485.9 463.8 482 452.5L344.1 315.7L329.2 330.6C279.9 379.9 200.1 379.9 150.8 330.6C127.8 307.6 126.9 270.7 148.6 246.6z"/></svg> Lend</span>
          </button>
        </div>

        <form class='donation-form' id='donation-form'>
          <div id='donate-content'>
            <div class='info-box'>
              <svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='#15803d' stroke-width='2'>
                <circle cx='12' cy='12' r='10'/>
                <path d='M12 16v-4M12 8h.01'/>
              </svg>
              <p class='info-box-text'>
                Make a charitable donation to support this cause. Donations are non-refundable gifts.
              </p>
            </div>

            <div class='form-group'>
              <label class='form-label' for='amount'>Donation Amount</label>
              <input type='number' id='amount' class='form-input' placeholder='Enter amount ($5 - $\${remainingAmount})' min='5' max='\${remainingAmount}' step='5' required />
              <div class='amount-suggestions'>
                <div class='amount-chip' data-amount='25'>$25</div>
                <div class='amount-chip' data-amount='50'>$50</div>
                <div class='amount-chip' data-amount='100'>$100</div>
                <div class='amount-chip' data-amount='250'>$250</div>
              </div>
            </div>
          </div>

          <div id='loan-content' style='display: none;'>
            <div class='info-box'>
              <svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='#15803d' stroke-width='2'>
                <circle cx='12' cy='12' r='10'/>
                <path d='M12 16v-4M12 8h.01'/>
              </svg>
              <p class='info-box-text'>
                Provide an interest-free loan (Qard Hasan) that will be repaid. Maximum loan amount: $\${widgetData.repaymentCapableAmount.toLocaleString()}
              </p>
            </div>

            <div class='form-group'>
              <label class='form-label' for='loan-amount'>Loan Amount</label>
              <input type='number' id='loan-amount' class='form-input' placeholder='Enter amount ($5 - $\${Math.min(widgetData.repaymentCapableAmount, remainingAmount)})' min='5' max='\${Math.min(widgetData.repaymentCapableAmount, remainingAmount)}' step='5' />
              <div class='amount-suggestions'>
                <div class='amount-chip' data-amount='50'>$50</div>
                <div class='amount-chip' data-amount='100'>$100</div>
                <div class='amount-chip' data-amount='250'>$250</div>
                <div class='amount-chip' data-amount='500'>$500</div>
              </div>
            </div>
          </div>

          <div class='form-group'>
            <label class='form-label' for='name'>Name (Optional)</label>
            <input type='text' id='name' class='form-input' placeholder='Your name' />
          </div>

          <div class='checkbox-container'>
            <input type='checkbox' id='intent-checkbox' class='checkbox-input' required />
            <label for='intent-checkbox' class='checkbox-label'>
              I am contributing purely to help, not for profit or material gain.
            </label>
          </div>

          <button type='submit' class='submit-button'>
            <span id='submit-text'>Proceed to Payment</span>
            <svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
              <path d='M5 12h14M12 5l7 7-7 7'/>
            </svg>
          </button>
        </form>

        <div class='powered-by'>
          Powered by <a href='https://qardhasana.com' target='_blank'>QardHasana</a>
        </div>
      </div>\`;

    document.body.appendChild(modalOverlay);

    // State
    let currentTab = 'donate';

    // Functions
    function openModal() {
      modalOverlay.style.display = "flex";
      setTimeout(() => modalOverlay.classList.add("show"), 10);
      document.body.style.overflow = 'hidden';
    }

    function closeModal() {
      modalOverlay.classList.remove("show");
      setTimeout(() => {
        modalOverlay.style.display = "none";
        document.body.style.overflow = '';
      }, 300);
    }

    function switchTab(tab) {
      currentTab = tab;
      const donateContent = document.getElementById('donate-content');
      const loanContent = document.getElementById('loan-content');
      const submitText = document.getElementById('submit-text');
      const tabs = document.querySelectorAll('.tab-button');

      tabs.forEach(t => {
        if (t.dataset.tab === tab) {
          t.classList.add('active');
        } else {
          t.classList.remove('active');
        }
      });

      if (tab === 'donate') {
        donateContent.style.display = 'block';
        loanContent.style.display = 'none';
        submitText.textContent = 'Proceed to Payment';
      } else {
        donateContent.style.display = 'none';
        loanContent.style.display = 'block';
        submitText.textContent = 'Proceed to Loan Agreement';
      }
    }

    function handleSubmit(e) {
      e.preventDefault();
      
      const name = document.getElementById('name').value;
      const intent = document.getElementById('intent-checkbox').checked;
      
      if (!intent) {
        alert('Please confirm your contribution intent');
        return;
      }

      let amount, type;
      if (currentTab === 'donate') {
        amount = document.getElementById('amount').value;
        type = 'donation';
      } else {
        amount = document.getElementById('loan-amount').value;
        type = 'loan';
      }

      if (!amount || amount < 5) {
        alert('Please enter a valid amount (minimum $5)');
        return;
      }

      // Build URL with parameters
      const baseUrl = window.location.origin;
      const params = new URLSearchParams({
        host: hostIdentifier,
        widget: widgetData.title,
        amount: amount,
        type: type,
        name: name || ''
      });
      
      const url = \`\${baseUrl}/contribute/\${hostIdentifier}?\${params.toString()}\`;
      window.open(url, '_blank');
      closeModal();
    }

    // Event listeners
    triggerContainer.querySelector("button").addEventListener("click", openModal);
    document.getElementById('close-modal').addEventListener("click", closeModal);
    
    modalOverlay.addEventListener("click", function(e) {
      if (e.target === modalOverlay) {
        closeModal();
      }
    });

    document.querySelectorAll('.tab-button').forEach(btn => {
      btn.addEventListener('click', () => switchTab(btn.dataset.tab));
    });

    document.querySelectorAll('.amount-chip').forEach(chip => {
      chip.addEventListener('click', function() {
        const amount = this.dataset.amount;
        if (currentTab === 'donate') {
          document.getElementById('amount').value = amount;
        } else {
          document.getElementById('loan-amount').value = amount;
        }
      });
    });

    document.getElementById('donation-form').addEventListener('submit', handleSubmit);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", renderWidget);
  } else {
    renderWidget();
  }
})();
`;

export async function handle(request: Request) {
  try {
    const url = new URL(request.url);
    const validatedInput = schema.parse({
      hostIdentifier: url.searchParams.get("hostIdentifier"),
    });

    // In production, fetch widget data from database
    // For now, using sample data
    const widgetData = {
      title: "Monthly Operating Expenses",
      goalAmount: 5000,
      repaymentCapableAmount: 3000,
      currentAmount: 1250,
    };

    const scriptContent = getWidgetScript(
      validatedInput.hostIdentifier || "sample",
      widgetData,
    );

    return new Response(scriptContent, {
      headers: {
        "Content-Type": "application/javascript; charset=utf-8",
        "Cache-Control": "public, max-age=3600",
        "Access-Control-Allow-Origin": "*",
      },
    });
  } catch (error) {
    console.error("Failed to generate widget script:", error);
    const errorMessage =
      error instanceof Error ? error.message : "An unknown error occurred";
    return new Response(superjson.stringify({ error: errorMessage }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }
}

export async function getAssetById(request: Request) {
  const session = await getServerUserSession(request);
  if (!session?.user) {
    return new Response("Unauthorized", { status: 401 });
  }

  // Use the shared query function
  // const asset = await getAssetByIdQuery("assetById", session.user.id);

  if (!asset) {
    return new Response("Asset not found", { status: 404 });
  }

  // Do something with the asset
  console.log(asset.fundGoal, asset.currentAmountRaised);

  return new Response("Success");
}
